require:
  - rubocop-rails
  - rubocop-performance

Rails:
  Enabled: true
AllCops:
  NewCops: enable
  DefaultFormatter: progress
  Exclude:
    - 'bin/**'
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'lib/tasks/**/*'
    - 'vendor/**/*'
    # - '**/*.erb'

Metrics/BlockLength:
  Exclude:
    - !ruby/regexp /.*_spec\.rb$/
    - 'spec/factories/**/*'
    - 'spec/**/*'
    - 'lib/tasks/*'
  CountComments: false

Metrics/MethodLength:
  ExcludedMethods: []
  CountComments: false
  Max: 15

Layout/LineLength:
  Max: 120
  Exclude:
  - !ruby/regexp /.*_spec\.rb$/

Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - !ruby/regexp /.*_spec\.rb$/

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
