Documentation:
  Enabled: false
Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.5
  DefaultFormatter: progress
  Exclude:
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - 'bin/**'
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
Metrics/BlockLength:
  Exclude:
    - !ruby/regexp /.*_spec\.rb$/
Metrics/LineLength:
  Max: 99
Style/BlockDelimiters:
  Exclude:
    - !ruby/regexp /.*_spec\.rb$/
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
