#!/bin/sh

# run command: cichecks

echo '==== RUNNING RSPEC ====='
bundle exec rspec

echo '==== RUNNING STANDARD RB ====='
bundle exec standardrb

echo '==== RUNNING CSS LINT ====='
bundle exec scss-lint app/assets/stylesheets/**.scss

echo 'DONE'
