#!/bin/sh

# run command: lint

echo '==== RUNNING RSPEC ====='
bundle exec rspec

echo '==== RUNNING RUBOCOP ====='
bundle exec rubocop

echo '==== RUNNING CSS LINT ====='
bundle exec scss-lint app/assets/stylesheets/**.scss

echo 'DONE'
